const fs = require('fs');

const map = {
  "Adyapith": "আদ্যাপীঠ",
  "Dakshineswar": "দক্ষিণেশ্বর",
  "Baranagar Netaji Colony": "বরাহনগর নেতাজি কলোনি",
  "Alambazar Sarbojanin": "আলমবাজার সার্বজনীন",
  "Noapara Sarbojanin": "নোয়াপাড়া সার্বজনীন",
  "Chowwddar Pally Sarbojanin": "চৌদ্দার পল্লী সার্বজনীন",
  "Sinthi Sarbojanin": "সিঁথি সার্বজনীন",
  "Tala Pratyay": "টালা প্রত্যয়",
  "Tala Park": "টালা পার্ক",
  "Natun Palli Pradeep Sangha": "নতুন পল্লী প্রদীপ সংঘ",
  "Netaji Sporting": "নেতাজি স্পোর্টিং",
  "Laketown Association": "লেকটাউন অ্যাসোসিয়েশন",
  "Bharatchakra": "ভারতচক্র",
  "Dum Dum Park": "দমদম পার্ক",
  "Sreebhumi": "শ্রীভূমি",
  "Baghbazaar": "বাগবাজার",
  "Shyam Square": "শ্যাম স্কোয়ার",
  "Jagat Mukherjee Park": "জগৎ মুখার্জী পার্ক",
  "Ahiritola": "আহিরীটোলা",
  "Beniatola": "বেনিয়াটোলা",
  "Kumartuli Park": "কুমারটুলি পার্ক",
  "Sovabazar Rajbari": "শোভাবাজার রাজবাড়ি",
  "Hatibagan Sarbojanin": "হাতিবাগান সার্বজনীন",
  "Telenga Bagan": "তেলেঙ্গা বাগান",
  "Chaltabagan": "চালতাবাগান",
  "Bedon Square": "বিডন স্কোয়ার",
  "Shimla Bayam Samity": "শিমলা ব্যায়াম সমিতি",
  "37 Pally": "৩৭ পল্লী",
  "Vivekananda Sporting": "বিবেকানন্দ স্পোর্টিং",
  "Rabindra Kanan": "রবীন্দ্র কানন",
  "Pathuriaghata Pather Panchali": "পাথুরিয়াঘাটা পথের পাঁচালী",
  "Md. Ali Park": "মোঃ আলী পার্ক",
  "Sealdah Railway Square Athletic Club": "শিয়ালদহ রেলওয়ে স্কোয়ার অ্যাথলেটিক ক্লাব",
  "Santosh Mitra Square": "সন্তোষ মিত্র স্কোয়ার",
  "Subodh Mullick Square": "সুবোধ মল্লিক স্কোয়ার",
  "Kapalitola": "কপালিতলা",
  "Janbazar": "জানবাজার",
  "Taltola Sarbojanin": "তালতলা সার্বজনীন",
  "Santosh Mitra Square (via walk)": "সন্তোষ মিত্র স্কোয়ার",
  "Muhammad Ali Park": "মুহাম্মদ আলী পার্ক",
  "Park Circus Sarbojanin (via auto)": "পার্ক সার্কাস সার্বজনীন",
  "Khidirpur 25 Pally (via auto)": "খিদিরপুর ২৫ পল্লী",
  "Ghorkel Sporting": "ঘোরকেল স্পোর্টিং",
  "Chakraberja Sarbojanin": "চক্রবেড়িয়া সার্বজনীন",
  "Harish Park": "হরিশ পার্ক",
  "22 Pally": "২২ পল্লী",
  "Padmapukur Youth Association": "পদ্মপুকুর ইয়ুথ অ্যাসোসিয়েশন",
  "Paddapukur Barwari Samiti": "পদ্মপুকুর বারোয়ারি সমিতি",
  "Bhawanipur Durgotsav": "ভবানীপুর দুর্গোৎসব",
  "75 Pally": "৭৫ পল্লী",
  "Maddox Square": "ম্যাডক্স স্কোয়ার",
  "76 Pally": "৭৬ পল্লী",
  "Ray Street Park": "রায় স্ট্রিট পার্ক",
  "Bhawanipur Swadhin Sangha": "ভবানীপুর স্বাধীন সংঘ",
  "Badamtala": "বাদামতলা",
  "23 Pally": "২৩ পল্লী",
  "Forward Club": "ফরওয়ার্ড ক্লাব",
  "Matri Mandir": "মাতৃ মন্দির",
  "Bakul Bagan Sarbojanin Durgotsav": "বকুল বাগান সার্বজনীন দুর্গোৎসব",
  "Badamtala Ashar Sangha": "বাদামতলা আষাঢ় সংঘ",
  "Samajsebi": "সমাজসেবী",
  "Ballygunge Cultural": "বালিগঞ্জ কালচারাল",
  "Ekdalia Evergreen": "একডালিয়া এভারগ্রিন",
  "Singhi Park": "সিংঘী পার্ক",
  "Adi Lake Pally": "আদি লেক পল্লী",
  "Mudiali Club": "মুদিয়ালি ক্লাব",
  "Shib Mandir": "শিব মন্দির",
  "Tridhara Sammilani": "ত্রিধারা সম্মিলনী",
  "Suruchi Sangha (via auto)": "সুরুচি সংঘ",
  "Babu Bagan": "বাবু বাগান",
  "Jodhpur Park": "যোধপুর পার্ক",
  "Kudghat Pratirodh Sangha": "কুঁদঘাট প্রতিরোধ সংঘ",
  "Maitree Park Sarbojanin": "মৈত্রী পার্ক সার্বজনীন",
  "Roynagar Unnayan Samity": "রয়নগর উন্নয়ন সমিতি",
  "Udayan Sangha": "উদয়ন সংঘ",
  "Pancha Durga Sarbojanin Durgotsav": "পঞ্চ দুর্গা সার্বজনীন দুর্গোৎসব",
  "Naba Durga Sarbojanin Durgotsav": "নব দুর্গা সার্বজনীন দুর্গোৎসব",
  "Briji Sarbojanin": "ব্রিজি সার্বজনীন",
  "Naktala Udayan Sangha": "নাকতলা উদয়ন সংঘ",
  "Baisakhi Sangha": "বৈশাখী সংঘ",
  "Howrah Maidan Sarbojanin": "হাওড়া ময়দান সার্বজনীন",
  "Howrah Railway Club": "হাওড়া রেলওয়ে ক্লাব",
  "Lalbazar Police Line": "লালবাজার পুলিশ লাইন",
  "Janbazar (walking distance)": "জানবাজার",
  "Sealdah Athletic Club": "শিয়ালদহ অ্যাথলেটিক ক্লাব",
  "Chaltabagan (via walk)": "চালতাবাগান",
  "Phoolbagan Sarbojanin": "ফুলবাগান সার্বজনীন",
  "Beleghata Sandhani": "বেলেঘাটা সন্ধানী",
  "Beleghata 33 Pally": "বেলেঘাটা ৩৩ পল্লী",
  "Mitali Kankurgachi": "মিতালী কাঁকুড়গাছি",
  "FD Block": "এফডি ব্লক",
  "FC Block": "এফসি ব্লক",
  "CG Block": "সিজি ব্লক",
  "BC Block": "বিসি ব্লক",
  "DC Block": "ডিসি ব্লক",
  "CA Block": "সিএ ব্লক",
  "Central Park Sarbojanin": "সেন্ট্রাল পার্ক সার্বজনীন",
  "AE Block Part 1": "এই ব্লক পার্ট ১",
  "BJ Block": "বিজে ব্লক",
  "AK Block": "একে ব্লক",
  "AG Block": "এজি ব্লক",
  "Mahisbathan Sarbojanin": "মഹിষবাথান সার্বজনীন",
  "Rajdanga Naba Uday Sangha": "রাজডাঙ্গা নব উদয় সংঘ",
  "Bosepukur Sitala Mandir": "বোসপুকুর শীতলা মন্দির",
  "Bosepukur Talbagan": "বোসপুকুর তালবাগান",
  "Kasba Shakti Sangha": "কসবা শক্তি সংঘ",
  "Kalikapur Sarbojanin": "কালিকাপুর সার্বজনীন",
  "Purbachal": "পূর্বাচল",
  "Mukundapur Sarbojanin": "মুকুন্দপুর সার্বজনীন",
  "Survey Park": "সার্ভে পার্ক",
  "Santoshpur Lake Pally": "সন্তোষপুর লেক পল্লী",
  "Joka Sarbojanin": "জোকা সার্বজনীন",
  "Thakurpukur State Bank Park": "ঠাকুরপুকুর স্টেট ব্যাংক পার্ক",
  "Behala Friends": "বেহালা ফ্রেন্ডস",
  "Barisha Youth Club": "বড়িশা ইয়ুথ ক্লাব",
  "Behala Nutan Dal": "বেহালা নূতন দল",
  "Barisha Sarbojanin": "বড়িশা সার্বজনীন",
  "Barisha Club": "বড়িশা ক্লাব",
  "Behala Club": "বেহালা ক্লাব",
  "Srishti": "সৃষ্টি",
  "Behala 29 Pally": "বেহালা ২৯ পল্লী",
  "Ajeya Sangha": "অজেয় সংঘ",
  "Alipore Sarbojanin": "আলিপুর সার্বজনীন"
};

const dataPath = 'c:/Users/LENOVO/Desktop/pujorpothe/src/lib/data.ts';
let dataTs = fs.readFileSync(dataPath, 'utf8');

for (const [eng, ben] of Object.entries(map)) {
  const target = `bengaliName: '${eng} পুজো'`;
  const replacement = `bengaliName: '${ben} পুজো'`;
  dataTs = dataTs.split(target).join(replacement);
  
  const target2 = `bengaliName: "${eng} পুজো"`;
  const replacement2 = `bengaliName: "${ben} পুজো"`;
  dataTs = dataTs.split(target2).join(replacement2);
}

fs.writeFileSync(dataPath, dataTs);
console.log('Translated to Bengali!');
